from django.urls import path
from .import views
urlpatterns = [
    path('',views.adminlogin, name='adminlogin'),
    path('login',views.adminlogin, name='adminlogin'),
    path('member',views.member, name='member'),
    path('deletemember/<int:admin_id>/',views.delete_member,name='delete_member'),
    path('register',views.adminregister, name='adminregister'),
    path('hall',views.hallmanage, name='hallmanage'),
    path('viewhall',views.viewhall, name='viewhall'),
    path('hall_detail/<int:id>/',views.hall_detail, name='halldetail'),
    path('upcoming',views.upcoming, name='upcoming'),
    path('history',views.history, name='history'),
    path('report',views.report, name='report'),
    path('generate-report/', views.generate_report, name='generate_report'),
    path('delete_hall/<int:id>/',views.delete_hall, name='delete_hall'),
    path('updatehall/<int:id>/',views.updatehall, name='updatehall'),
    path('feature',views.featuremanage, name='featuremanage'),
    path('inoperability',views.hallinoperabilitymanage, name='hallinoperabilitymanage'),
    path('update_inoperability/<int:id>/',views.update_inoperability, name='update_inoperability'),
    path('delete_inoperability/<int:id>/',views.delete_inoperability, name='delete_inoperability'),
    path('payment',views.paymentmanage, name='paymentmanage'),
    path('update_feature/<int:id>/',views.update_feature, name='update_feature'),
    path('delete_feature/<int:id>/',views.delete_feature, name='delete_feature'),
    path('admin_calendar/', views.calendarview, name='calendarview'),
    path('cal', views.cal, name='cal'),
    path('get_bookings/<int:hall_id>/', views.get_bookings, name='get_bookings'),
    path('booked', views.booked, name='booked'),
    path('viewbooklist/<int:id>/', views.viewbooklist, name='viewbooklist'),
    path('approve/<int:id>/',views.approve, name='approve'),
    path('logout',views.logout, name='logout'),
    path('generate_pdf/', views.generate_pdf, name='generate_pdf'),
    path('print_booking/<int:id>/', views.print_booking, name='print_booking'),
    path('inoperability_report/', views.inoperability_report, name='inoperability_report'),
    path('generate_individual_inoperability_pdf/<int:id>/', views.generate_individual_inoperability_pdf, name='generate_individual_inoperability_pdf'),
    path('generate_inoperability_pdf/', views.generate_inoperability_pdf, name='generate_inoperability_pdf'),
    
]

